/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyectofinal.vistas;

import java.util.Arrays;
import javax.swing.ComboBoxModel;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import proyectofinal.enums.EstadoTickete;
import proyectofinal.objetos.Ticket;
import proyectofinal.utilidades.Data;

/**
 *
 * @author ulacit
 */
public class InformacionTickets extends javax.swing.JFrame {

    /**
     * Creates new form InformacionTickets
     */
    
    private int id;
    private Ticket ticket;
    
    
    public InformacionTickets(int id) {
        // inicializar componentes de la vista
        initComponents();
        this.setLocationRelativeTo(null);
        this.setVisible(true);
        
        this.id = id;
        actualizarVista();
    }
    private void actualizarTickete(){
        try {
            EstadoTickete estado = EstadoTickete.valueOf(CmbxEstadoCaso.getSelectedItem().toString());
            System.out.println(estado);
            if(Data.TICKETES.actualizarTicket(id, TxtNuevaActualizacion.getText(), estado)) {
                JOptionPane.showMessageDialog(null, "Tickete actualizado correctamente!");
                actualizarVista();    
            } else {
                JOptionPane.showMessageDialog(null, "No se pudo actualizar el tickete");
            }
        } catch(Exception ex){
            JOptionPane.showMessageDialog(null, "No se pudo actualizar el tickete");
        }

    }
    private void actualizarVista(){
        // extrae el tickete por id
        ticket = Data.TICKETES.busquedaTicketPorID(id);
        TxtIdTicket.setText(Integer.toString(ticket.getId()));
        TxtDescripcion.setText(ticket.getDescripcion());
        TxtEmailCliente.setText(ticket.getCreadoPor().getCorreo());
        TxtNombreCliente.setText(ticket.getCreadoPor().getNombre() + " " + ticket.getCreadoPor().getApellidos());
        TxtHistorialCaso.setText(ticket.getHistorial());
        
        // se elige el estado del tickete en el combobox
        switch(ticket.getEstado()){
            case EN_PROGRESO:
                CmbxEstadoCaso.setSelectedIndex(1);
                break;
            case ESPERANDO_RESPUESTA:
                CmbxEstadoCaso.setSelectedIndex(2);
                break;
            case COMPLETADO:
                CmbxEstadoCaso.setSelectedIndex(3);
                break;
            default:
                CmbxEstadoCaso.setSelectedIndex(0);
                break; 
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        TxtIdTicket = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        TxtDescripcion = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        TxtNombreCliente = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        TxtEmailCliente = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        TxttelefonoCliente = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        CmbxEstadoCaso = new javax.swing.JComboBox<String>();
        jScrollPane1 = new javax.swing.JScrollPane();
        TxtNuevaActualizacion = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        TxtHistorialCaso = new javax.swing.JTextArea();
        BtnActualizarCaso = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("ID Ticket:");

        TxtIdTicket.setEditable(false);

        jLabel2.setText("Descripción:");

        TxtDescripcion.setEditable(false);

        jLabel3.setText("Nombre:");

        TxtNombreCliente.setEditable(false);

        jLabel4.setText("Email:");

        TxtEmailCliente.setEditable(false);

        jLabel5.setText("Teléfono:");

        TxttelefonoCliente.setEditable(false);

        jLabel6.setText("Estado del caso:");

        CmbxEstadoCaso.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "PENDIENTE", "EN_PROGRESO", "ESPERANDO_RESPUESTA", "COMPLETADO" }));

        TxtNuevaActualizacion.setColumns(20);
        TxtNuevaActualizacion.setRows(5);
        jScrollPane1.setViewportView(TxtNuevaActualizacion);

        TxtHistorialCaso.setEditable(false);
        TxtHistorialCaso.setColumns(20);
        TxtHistorialCaso.setRows(5);
        jScrollPane2.setViewportView(TxtHistorialCaso);

        BtnActualizarCaso.setText("Actualizar Caso");
        BtnActualizarCaso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnActualizarCasoActionPerformed(evt);
            }
        });

        jLabel7.setText("Nueva Actualización:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TxtNombreCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TxtDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 337, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(284, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(BtnActualizarCaso))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(22, 22, 22)
                                .addComponent(TxtIdTicket, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel6)
                                .addGap(18, 18, 18)
                                .addComponent(CmbxEstadoCaso, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel4))
                                .addGap(22, 22, 22)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(TxtEmailCliente, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                                    .addComponent(TxttelefonoCliente))
                                .addGap(129, 129, 129)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel7)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addComponent(jScrollPane1))))
                        .addGap(20, 20, 20))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(TxtIdTicket, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(CmbxEstadoCaso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(TxtDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(TxtNombreCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(TxtEmailCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(TxttelefonoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addComponent(BtnActualizarCaso)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 211, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnActualizarCasoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnActualizarCasoActionPerformed
        actualizarTickete();
    }//GEN-LAST:event_BtnActualizarCasoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnActualizarCaso;
    private javax.swing.JComboBox<String> CmbxEstadoCaso;
    private javax.swing.JTextField TxtDescripcion;
    private javax.swing.JTextField TxtEmailCliente;
    private javax.swing.JTextArea TxtHistorialCaso;
    private javax.swing.JTextField TxtIdTicket;
    private javax.swing.JTextField TxtNombreCliente;
    private javax.swing.JTextArea TxtNuevaActualizacion;
    private javax.swing.JTextField TxttelefonoCliente;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
