/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyectofinal.vistas;

import java.util.Arrays;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import proyectofinal.utilidades.Data;
import proyectofinal.utilidades.InformacionUsuario;

/**
 *
 * @author Xtreme Pc
 */
public class ListaTicketsCliente extends javax.swing.JFrame {

    /**
     * Creates new form ListaTicketsCliente
     */
    public ListaTicketsCliente() {
        initComponents();
        
        
        this.setLocationRelativeTo(null);

        cargarTicketes();

        LblUsuarioLogueado.setText(InformacionUsuario.usuario.getNombre() + " " + InformacionUsuario.usuario.getApellidos());
    }
    
    public void cargarTicketes() {
        // se extrae la lista de ticketes del usuario usando el id
        String[] listaTicketes = Data.TICKETES.extraeTicketsPorCLiente(InformacionUsuario.usuario.getNombre(), InformacionUsuario.usuario.getApellidos());

        Vector fileVector = new Vector();
        for (String ticket : listaTicketes) {
            fileVector.add(new Vector(Arrays.asList(ticket.toString().split(","))));
        }

        Vector headings = new Vector();
        headings.add("Id");
        headings.add("Descripción");
        headings.add("Estado");
        headings.add("Cliente");

        DefaultTableModel model = new DefaultTableModel(fileVector, headings);
        TableTickets.setModel(model);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        TableTickets = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        LblUsuarioLogueado = new javax.swing.JLabel();
        BtnActualizar = new javax.swing.JButton();
        BtnIngresarNuevoTicket1 = new javax.swing.JButton();
        BtnLogOut = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        TableTickets.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "Descripción", "Estado", "Cliente"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        TableTickets.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TableTicketsMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TableTickets);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Usuario:");

        LblUsuarioLogueado.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        LblUsuarioLogueado.setText("\"\"");

        BtnActualizar.setText("Actualizar");
        BtnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnActualizarActionPerformed(evt);
            }
        });

        BtnIngresarNuevoTicket1.setText("Nuevo Ticket");
        BtnIngresarNuevoTicket1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnIngresarNuevoTicket1ActionPerformed(evt);
            }
        });

        BtnLogOut.setText("Salir");
        BtnLogOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnLogOutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(BtnActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 666, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(LblUsuarioLogueado))
                            .addComponent(BtnLogOut))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(571, Short.MAX_VALUE)
                    .addComponent(BtnIngresarNuevoTicket1)
                    .addGap(20, 20, 20)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(LblUsuarioLogueado))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BtnLogOut)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 71, Short.MAX_VALUE)
                .addComponent(BtnActualizar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(21, 21, 21)
                    .addComponent(BtnIngresarNuevoTicket1)
                    .addContainerGap(433, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TableTicketsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TableTicketsMouseClicked
        // TODO add your handling code here:
        try {
            DefaultTableModel model = (DefaultTableModel) TableTickets.getModel();
            int filaSeleccionada = TableTickets.getSelectedRow();
            int id = Integer.parseInt(model.getValueAt(filaSeleccionada, 0).toString());
            InformacionTickets info = new InformacionTickets(id, model.getValueAt(filaSeleccionada, 2).toString());
            info.show();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Acción no válida");
        }
    }//GEN-LAST:event_TableTicketsMouseClicked

    private void BtnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnActualizarActionPerformed
        // TODO add your handling code here:
        cargarTicketes();
    }//GEN-LAST:event_BtnActualizarActionPerformed

    private void BtnIngresarNuevoTicket1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnIngresarNuevoTicket1ActionPerformed
        // TODO add your handling code here:
        AgregarNuevoTicket nuevo = new AgregarNuevoTicket();
        nuevo.show();
    }//GEN-LAST:event_BtnIngresarNuevoTicket1ActionPerformed

    private void BtnLogOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnLogOutActionPerformed
        // TODO add your handling code here:
        Login login = new Login();
        InformacionUsuario.usuario = null;
        this.dispose();
        login.show();
    }//GEN-LAST:event_BtnLogOutActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnActualizar;
    private javax.swing.JButton BtnIngresarNuevoTicket1;
    private javax.swing.JButton BtnLogOut;
    private javax.swing.JLabel LblUsuarioLogueado;
    private javax.swing.JTable TableTickets;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
